// ============================================
// ICON COMPONENTS (Lucide React wrappers)
// ============================================

import { 
  Home, FileText, ClipboardList, Users, Calculator, Box, 
  UserCog, ShieldAlt, BarChart3, Settings, FileInvoice, 
  Truck, CalendarCheck, ThLarge, BoxSelect, Coins, 
  FileInvoiceDollar, Plus, Edit, Trash2, Eye, Search, 
  Save, Printer, X, Check, ChevronLeft, ChevronRight, 
  Menu, Bell, LogOut, Download, Upload, RefreshCw, 
  Filter, ArrowUpDown, MoreHorizontal, Phone, Mail, 
  MapPin, CreditCard, DollarSign, TrendingUp, TrendingDown,
  Package, Layers, Grid, List, Calendar, Clock, User,
  Lock, Unlock, AlertCircle, CheckCircle, XCircle, Info,
  HelpCircle, ExternalLink, Copy, Share2, Heart, Star,
  Sun, Moon, Monitor, Smartphone, Tablet, Laptop,
  Wifi, WifiOff, Battery, BatteryCharging, BatteryWarning,
  Volume2, VolumeX, Mic, MicOff, Camera, CameraOff,
  Video, VideoOff, PhoneCall, PhoneOff, MessageSquare,
  Send, MailOpen, Inbox, Archive, Trash, Folder, File,
  Image, Music, Film, Play, Pause, SkipForward, SkipBack,
  Repeat, Shuffle, Volume1, Volume, Maximize, Minimize,
  Maximize2, Minimize2, Move, RotateCcw, RotateCw, ZoomIn,
  ZoomOut, Crosshair, Target, Aperture, Focus, Crop,
  Scissors, Type, Bold, Italic, Underline, AlignLeft,
  AlignCenter, AlignRight, AlignJustify, List as ListIcon,
  ListOrdered, Indent, Outdent, Link, Paperclip, Quote,
  Code, Code2, Terminal, Hash, At, Pound, Euro, 
  IndianRupee, Percent, PlusCircle, MinusCircle, 
  PlusSquare, MinusSquare, CheckSquare, Square,
  Circle, Disc, Triangle, Hexagon, Octagon, Pentagon,
  Star as StarIcon, Flag, Bookmark, Tag, Award, Trophy,
  Medal, Crown, Gem, Gift, ShoppingCart, ShoppingBag,
  Store, Building, Building2, Home as HomeIcon, 
  Warehouse, Factory, Landmark, Landmark2, Banknote,
  Receipt, Wallet, PiggyBank, BanknoteIcon, CoinsIcon,
  Bitcoin, CreditCardIcon, LandmarkIcon, ArrowLeft,
  ArrowRight, ArrowUp, ArrowDown, ArrowUpLeft,
  ArrowUpRight, ArrowDownLeft, ArrowDownRight,
  ChevronsLeft, ChevronsRight, ChevronsUp, ChevronsDown,
  CornerDownLeft, CornerDownRight, CornerUpLeft,
  CornerUpRight, CornerLeftDown, CornerLeftUp,
  CornerRightDown, CornerRightUp, GitCommit, GitBranch,
  GitMerge, GitPullRequest, GitFork, Github, Gitlab,
  Codepen, Codesandbox, Figma, Framer, Slack, Trello,
  Chrome, Firefox, Safari, Edge, Globe, Map, Navigation,
  Compass, Locate, LocateFixed, MapPinIcon, Navigation2,
  Plane, Train, Bus, Car, TruckIcon, Ship, Anchor,
  Fuel, Gauge, GaugeCircle, Activity, HeartPulse,
  Stethoscope, Pill, Syringe, Thermometer, Droplets,
  Droplet, Flame, Snowflake, Wind, Cloud, CloudRain,
  CloudSnow, CloudLightning, Sun as SunIcon, Moon as MoonIcon,
  Sunrise, Sunset, Umbrella, ThermometerSun, ThermometerSnowflake,
  Eye as EyeIcon, EyeOff, Glasses, Scan, ScanLine, ScanFace,
  Fingerprint, Key, LockIcon, UnlockIcon, Shield, ShieldCheck,
  ShieldAlert, ShieldX, ShieldQuestion, ShieldOff, Sword,
  Swords, Bomb, Rocket, Zap, ZapOff, Plug, Plug2, PlugZap,
  BatteryIcon, BatteryMedium, BatteryFull, BatteryLow,
  Cpu, HardDrive, Database, Server, Network, WifiIcon,
  WifiOff as WifiOffIcon, Radio, Antenna, Satellite,
  Bluetooth, BluetoothConnected, BluetoothOff, Usb,
  HDMI, Cable, MonitorIcon, MonitorSmartphone, 
  MonitorSpeaker, Tv, Projector, Speaker, Headphones,
  Gamepad2, Joystick, Keyboard, Mouse, Watch, WatchIcon,
  GlassWater, Beer, Coffee, CupSoda, Soup, Utensils,
  UtensilsCrossed, Pizza, Sandwich, IceCream, Cookie,
  Candy, Cherry, Grape, Apple, Citrus, Carrot, Salad,
  Beef, Fish, Egg, Milk, Wheat, SandwichIcon, Croissant,
  ChefHat, FlameKindling, FireExtinguisher, Siren, AlertTriangle,
  AlertOctagon, Skull, Ghost, Cat, Dog, Bird, FishIcon,
  Bug, Spider, Snail, Turtle, Rabbit, Squirrel, Rat,
  Pig, Cow, Sheep, Chicken, Horse, Elephant, Giraffe,
  Lion, Tiger, Bear, Wolf, Fox, Deer, Monkey, Gorilla,
  Panda, Koala, Kangaroo, Crocodile, Hippo, Rhino,
  Zebra, Peacock, Eagle, Owl, Penguin, Parrot, Butterfly,
  Bee, Beetle, Ant, Mosquito, Fly, Worm, Shell, SnailIcon,
  Feather, Flower, Flower2, TreePine, TreeDeciduous, TreePalm,
  Cactus, Mountain, Volcano, Waves, Tsunami, Tornado,
  Hurricane, Earthquake, Flood, Drought, Wildfire, Meteor,
  Comet, MoonStar, Eclipse, Orbit, Atom, Microscope,
  Telescope, SatelliteDish, Radar, RadioTower, Broadcast,
  Signal, SignalHigh, SignalMedium, SignalLow, SignalZero,
  BluetoothSearching, BluetoothDisabled, Airplay, Cast,
  Chromecast, ScreenShare, Presentation, Slideshow, 
  ProjectorIcon, CameraIcon, VideoIcon, FilmIcon, 
  Clapperboard, Popcorn, Ticket, Drama, Music2, 
  Music3, Music4, RadioIcon, Podcast, Mic2, Headset,
  VolumeX as VolumeXIcon, Volume1 as Volume1Icon,
  Volume2 as Volume2Icon, Volume as VolumeIcon,
  Maximize as MaximizeIcon, Minimize as MinimizeIcon
} from 'lucide-react';

// Export all icons
export {
  Home, FileText, ClipboardList, Users, Calculator, Box,
  UserCog, ShieldAlt, BarChart3, Settings, FileInvoice,
  Truck, CalendarCheck, ThLarge, BoxSelect, Coins,
  FileInvoiceDollar, Plus, Edit, Trash2, Eye, Search,
  Save, Printer, X, Check, ChevronLeft, ChevronRight,
  Menu, Bell, LogOut, Download, Upload, RefreshCw,
  Filter, ArrowUpDown, MoreHorizontal, Phone, Mail,
  MapPin, CreditCard, DollarSign, TrendingUp, TrendingDown,
  Package, Layers, Grid, List, Calendar, Clock, User,
  Lock, Unlock, AlertCircle, CheckCircle, XCircle, Info,
  HelpCircle, ExternalLink, Copy, Share2, Heart, Star,
  Sun, Moon, Monitor, Smartphone, Tablet, Laptop,
  Wifi, WifiOff, Battery, BatteryCharging, BatteryWarning,
  Volume2, VolumeX, Mic, MicOff, Camera, CameraOff,
  Video, VideoOff, PhoneCall, PhoneOff, MessageSquare,
  Send, MailOpen, Inbox, Archive, Trash, Folder, File,
  Image, Music, Film, Play, Pause, SkipForward, SkipBack,
  Repeat, Shuffle, Volume1, Volume, Maximize, Minimize,
  Maximize2, Minimize2, Move, RotateCcw, RotateCw, ZoomIn,
  ZoomOut, Crosshair, Target, Aperture, Focus, Crop,
  Scissors, Type, Bold, Italic, Underline, AlignLeft,
  AlignCenter, AlignRight, AlignJustify, ListIcon,
  ListOrdered, Indent, Outdent, Link, Paperclip, Quote,
  Code, Code2, Terminal, Hash, At, Pound, Euro,
  IndianRupee, Percent, PlusCircle, MinusCircle,
  PlusSquare, MinusSquare, CheckSquare, Square,
  Circle, Disc, Triangle, Hexagon, Octagon, Pentagon,
  StarIcon, Flag, Bookmark, Tag, Award, Trophy,
  Medal, Crown, Gem, Gift, ShoppingCart, ShoppingBag,
  Store, Building, Building2, HomeIcon,
  Warehouse, Factory, Landmark, Landmark2, Banknote,
  Receipt, Wallet, PiggyBank, BanknoteIcon, CoinsIcon,
  Bitcoin, CreditCardIcon, LandmarkIcon, ArrowLeft,
  ArrowRight, ArrowUp, ArrowDown, ArrowUpLeft,
  ArrowUpRight, ArrowDownLeft, ArrowDownRight,
  ChevronsLeft, ChevronsRight, ChevronsUp, ChevronsDown,
  CornerDownLeft, CornerDownRight, CornerUpLeft,
  CornerUpRight, CornerLeftDown, CornerLeftUp,
  CornerRightDown, CornerRightUp, GitCommit, GitBranch,
  GitMerge, GitPullRequest, GitFork, Github, Gitlab,
  Codepen, Codesandbox, Figma, Framer, Slack, Trello,
  Chrome, Firefox, Safari, Edge, Globe, Map, Navigation,
  Compass, Locate, LocateFixed, MapPinIcon, Navigation2,
  Plane, Train, Bus, Car, TruckIcon, Ship, Anchor,
  Fuel, Gauge, GaugeCircle, Activity, HeartPulse,
  Stethoscope, Pill, Syringe, Thermometer, Droplets,
  Droplet, Flame, Snowflake, Wind, Cloud, CloudRain,
  CloudSnow, CloudLightning, SunIcon, MoonIcon,
  Sunrise, Sunset, Umbrella, ThermometerSun, ThermometerSnowflake,
  EyeIcon, EyeOff, Glasses, Scan, ScanLine, ScanFace,
  Fingerprint, Key, LockIcon, UnlockIcon, Shield, ShieldCheck,
  ShieldAlert, ShieldX, ShieldQuestion, ShieldOff, Sword,
  Swords, Bomb, Rocket, Zap, ZapOff, Plug, Plug2, PlugZap,
  BatteryIcon, BatteryMedium, BatteryFull, BatteryLow,
  Cpu, HardDrive, Database, Server, Network, WifiIcon,
  WifiOffIcon, Radio, Antenna, Satellite,
  Bluetooth, BluetoothConnected, BluetoothOff, Usb,
  HDMI, Cable, MonitorIcon, MonitorSmartphone,
  MonitorSpeaker, Tv, Projector, Speaker, Headphones,
  Gamepad2, Joystick, Keyboard, Mouse, Watch, WatchIcon,
  GlassWater, Beer, Coffee, CupSoda, Soup, Utensils,
  UtensilsCrossed, Pizza, Sandwich, IceCream, Cookie,
  Candy, Cherry, Grape, Apple, Citrus, Carrot, Salad,
  Beef, Fish, Egg, Milk, Wheat, SandwichIcon, Croissant,
  ChefHat, FlameKindling, FireExtinguisher, Siren, AlertTriangle,
  AlertOctagon, Skull, Ghost, Cat, Dog, Bird, FishIcon,
  Bug, Spider, Snail, Turtle, Rabbit, Squirrel, Rat,
  Pig, Cow, Sheep, Chicken, Horse, Elephant, Giraffe,
  Lion, Tiger, Bear, Wolf, Fox, Deer, Monkey, Gorilla,
  Panda, Koala, Kangaroo, Crocodile, Hippo, Rhino,
  Zebra, Peacock, Eagle, Owl, Penguin, Parrot, Butterfly,
  Bee, Beetle, Ant, Mosquito, Fly, Worm, Shell, SnailIcon,
  Feather, Flower, Flower2, TreePine, TreeDeciduous, TreePalm,
  Cactus, Mountain, Volcano, Waves, Tsunami, Tornado,
  Hurricane, Earthquake, Flood, Drought, Wildfire, Meteor,
  Comet, MoonStar, Eclipse, Orbit, Atom, Microscope,
  Telescope, SatelliteDish, Radar, RadioTower, Broadcast,
  Signal, SignalHigh, SignalMedium, SignalLow, SignalZero,
  BluetoothSearching, BluetoothDisabled, Airplay, Cast,
  Chromecast, ScreenShare, Presentation, Slideshow,
  ProjectorIcon, CameraIcon, VideoIcon, FilmIcon,
  Clapperboard, Popcorn, Ticket, Drama, Music2,
  Music3, Music4, RadioIcon, Podcast, Mic2, Headset,
  VolumeXIcon, Volume1Icon, Volume2Icon, VolumeIcon,
  MaximizeIcon, MinimizeIcon
};

// Icon mapper for dynamic usage
export const iconMap: Record<string, React.ComponentType<{ className?: string; size?: number }>> = {
  Home,
  FileInvoiceDollar,
  FileText,
  ClipboardList,
  Users,
  Calculator,
  Box,
  UserCog,
  ShieldAlt,
  BarChart3,
  Settings,
  FileInvoice,
  Truck,
  CalendarCheck,
  ThLarge,
  BoxSelect,
  Coins,
  Plus,
  Edit,
  Trash2,
  Eye,
  Search,
  Save,
  Printer,
  X,
  Check,
  ChevronLeft,
  ChevronRight,
  Menu,
  Bell,
  LogOut,
  Download,
  Upload,
  RefreshCw,
  Filter,
  ArrowUpDown,
  MoreHorizontal,
  Phone,
  Mail,
  MapPin,
  CreditCard,
  DollarSign,
  TrendingUp,
  TrendingDown,
  Package,
  Layers,
  Grid,
  List,
  Calendar,
  Clock,
  User,
  Lock,
  Unlock,
  AlertCircle,
  CheckCircle,
  XCircle,
  Info,
  HelpCircle,
  ExternalLink,
  Copy,
  Share2,
  Heart,
  Star,
  Sun,
  Moon,
  Monitor,
  Smartphone,
  Tablet,
  Laptop,
  Wifi,
  WifiOff,
  Battery,
  BatteryCharging,
  BatteryWarning,
  Volume2,
  VolumeX,
  Mic,
  MicOff,
  Camera,
  CameraOff,
  Video,
  VideoOff,
  PhoneCall,
  PhoneOff,
  MessageSquare,
  Send,
  MailOpen,
  Inbox,
  Archive,
  Trash,
  Folder,
  File,
  Image,
  Music,
  Film,
  Play,
  Pause,
  SkipForward,
  SkipBack,
  Repeat,
  Shuffle,
  Volume1,
  Volume,
  Maximize,
  Minimize,
  Maximize2,
  Minimize2,
  Move,
  RotateCcw,
  RotateCw,
  ZoomIn,
  ZoomOut,
  Crosshair,
  Target,
  Aperture,
  Focus,
  Crop,
  Scissors,
  Type,
  Bold,
  Italic,
  Underline,
  AlignLeft,
  AlignCenter,
  AlignRight,
  AlignJustify,
  List: ListIcon,
  ListOrdered,
  Indent,
  Outdent,
  Link,
  Paperclip,
  Quote,
  Code,
  Code2,
  Terminal,
  Hash,
  At,
  Pound,
  Euro,
  IndianRupee,
  Percent,
  PlusCircle,
  MinusCircle,
  PlusSquare,
  MinusSquare,
  CheckSquare,
  Square,
  Circle,
  Disc,
  Triangle,
  Hexagon,
  Octagon,
  Pentagon,
  StarIcon,
  Flag,
  Bookmark,
  Tag,
  Award,
  Trophy,
  Medal,
  Crown,
  Gem,
  Gift,
  ShoppingCart,
  ShoppingBag,
  Store,
  Building,
  Building2,
  HomeIcon,
  Warehouse,
  Factory,
  Landmark,
  Landmark2,
  Banknote,
  Receipt,
  Wallet,
  PiggyBank,
  Bitcoin,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  ArrowDown,
  ArrowUpLeft,
  ArrowUpRight,
  ArrowDownLeft,
  ArrowDownRight,
  ChevronsLeft,
  ChevronsRight,
  ChevronsUp,
  ChevronsDown,
  CornerDownLeft,
  CornerDownRight,
  CornerUpLeft,
  CornerUpRight,
  CornerLeftDown,
  CornerLeftUp,
  CornerRightDown,
  CornerRightUp,
  Globe,
  Map,
  Navigation,
  Compass,
  Locate,
  LocateFixed,
  Navigation2,
  Plane,
  Train,
  Bus,
  Car,
  Ship,
  Anchor,
  Fuel,
  Gauge,
  GaugeCircle,
  Activity,
  HeartPulse,
  Stethoscope,
  Pill,
  Syringe,
  Thermometer,
  Droplets,
  Droplet,
  Flame,
  Snowflake,
  Wind,
  Cloud,
  CloudRain,
  CloudSnow,
  CloudLightning,
  Sunrise,
  Sunset,
  Umbrella,
  ThermometerSun,
  ThermometerSnowflake,
  EyeIcon,
  EyeOff,
  Glasses,
  Scan,
  ScanLine,
  ScanFace,
  Fingerprint,
  Key,
  LockIcon,
  UnlockIcon,
  Shield,
  ShieldCheck,
  ShieldAlert,
  ShieldX,
  ShieldQuestion,
  ShieldOff,
  Sword,
  Swords,
  Bomb,
  Rocket,
  Zap,
  ZapOff,
  Plug,
  Plug2,
  PlugZap,
  BatteryIcon,
  BatteryMedium,
  BatteryFull,
  BatteryLow,
  Cpu,
  HardDrive,
  Database,
  Server,
  Network,
  Radio,
  Antenna,
  Satellite,
  Bluetooth,
  BluetoothConnected,
  BluetoothOff,
  Usb,
  HDMI,
  Cable,
  MonitorIcon,
  MonitorSmartphone,
  MonitorSpeaker,
  Tv,
  Projector,
  Speaker,
  Headphones,
  Gamepad2,
  Joystick,
  Keyboard,
  Mouse,
  Watch,
  WatchIcon,
  GlassWater,
  Beer,
  Coffee,
  CupSoda,
  Soup,
  Utensils,
  UtensilsCrossed,
  Pizza,
  Sandwich,
  IceCream,
  Cookie,
  Candy,
  Cherry,
  Grape,
  Apple,
  Citrus,
  Carrot,
  Salad,
  Beef,
  Fish,
  Egg,
  Milk,
  Wheat,
  Croissant,
  ChefHat,
  FlameKindling,
  FireExtinguisher,
  Siren,
  AlertTriangle,
  AlertOctagon,
  Skull,
  Ghost,
  Cat,
  Dog,
  Bird,
  Bug,
  Spider,
  Snail,
  Turtle,
  Rabbit,
  Squirrel,
  Rat,
  Pig,
  Cow,
  Sheep,
  Chicken,
  Horse,
  Elephant,
  Giraffe,
  Lion,
  Tiger,
  Bear,
  Wolf,
  Fox,
  Deer,
  Monkey,
  Gorilla,
  Panda,
  Koala,
  Kangaroo,
  Crocodile,
  Hippo,
  Rhino,
  Zebra,
  Peacock,
  Eagle,
  Owl,
  Penguin,
  Parrot,
  Butterfly,
  Bee,
  Beetle,
  Ant,
  Mosquito,
  Fly,
  Worm,
  Shell,
  SnailIcon,
  Feather,
  Flower,
  Flower2,
  TreePine,
  TreeDeciduous,
  TreePalm,
  Cactus,
  Mountain,
  Volcano,
  Waves,
  Tsunami,
  Tornado,
  Hurricane,
  Earthquake,
  Flood,
  Drought,
  Wildfire,
  Meteor,
  Comet,
  MoonStar,
  Eclipse,
  Orbit,
  Atom,
  Microscope,
  Telescope,
  SatelliteDish,
  Radar,
  RadioTower,
  Broadcast,
  Signal,
  SignalHigh,
  SignalMedium,
  SignalLow,
  SignalZero,
  BluetoothSearching,
  BluetoothDisabled,
  Airplay,
  Cast,
  Chromecast,
  ScreenShare,
  Presentation,
  Slideshow,
  Clapperboard,
  Popcorn,
  Ticket,
  Drama,
  Music2,
  Music3,
  Music4,
  Podcast,
  Mic2,
  Headset
};

// Get icon by name
export function getIcon(name: string): React.ComponentType<{ className?: string; size?: number }> | null {
  return iconMap[name] || null;
}
